### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] in node_modules/extract-zip

### ISSUE THREAD

**Issue by baob** [springernature/llamabot#4]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (<whatever>/llamabot/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
```

**Comment by baob** [comment]
Resolved by running node version 12 after reading this: https://github.com/giggio/node-chromedriver/issues/261
